---
- name: Install firewall if missing
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when: not firewall_installed

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
