---
- name: Get the allowed ports, service and default zone
  ansible.builtin.command: "{{ item }}"
  register: now_all
  loop:
    - firewall-cmd --list-ports
    - firewall-cmd --list-services
    - firewall-cmd --get-default-zone
  changed_when: false

- name: Convert outputs to facts
  ansible.builtin.set_fact:
    now_ports: "{{ now_all.results[0].stdout.split() }}"
    now_services: "{{ now_all.results[1].stdout.split() }}"
    now_zone: "{{ now_all.results[2].stdout }}"
  changed_when: false

- name: Checking service status
  ansible.builtin.command: "systemctl is-active firewalld"
  register: now_active
  changed_when: false

- name: Checking service enabled
  ansible.builtin.command: "systemctl is-enabled firewalld"
  register: now_enabled
  changed_when: false
