---
- name: Checking validity of current configuration
  ansible.builtin.command: authselect check
  register: curr_conf
  changed_when: false

- name: Register output of /etc/security/pwquality.conf
  ansible.builtin.shell: cat /etc/security/pwquality.conf | grep -v "^#"
  register: pwquality_out
  changed_when: false

- name: Register output of /etc/security/faillock.conf
  ansible.builtin.shell: cat /etc/security/faillock.conf | grep -v "^#"
  register: faillock_out
  changed_when: false

- name: Register output of login defaults
  ansible.builtin.shell: cat /etc/login.defs | grep -v "^#"
  register: logindef_out
  changed_when: false
