password_policy_password_min_length: '12'
password_policy_min_num_digit: '-1'
password_policy_min_upper_case: '-1'
password_policy_min_lower_case: '-1'
password_policy_min_oth_char: '-1'
password_policy_min_num_class: '4'
password_policy_brute_force_num: '3'
password_policy_time_within_check: '900'
password_policy_time_to_unlock: '600'
password_policy_time_to_unlock_root: '600'
password_policy_password_min_days: '2'
password_policy_password_max_days: '90'
password_policy_password_warn_days: '15'
